### ISSUE TITLE
Type definitions seems to be a mistake

### ISSUE THREAD

**Issue by SteveYuOWO** [markcellus/cookie-store#145] opened 2021-11-02 04:35 UTC
Shows typescript error
```
window.cookieStore.set({
  name: 'cookieConsents',
  value: '12345',
  expires,
});
```
Why just only support `set(name: string, value: string)`, not support payload ?
I see master branch is support `set(init: CookieListItem | string, possibleValue?: string)`

**Comment by markcellus** [comment] 2021-11-04 20:51
Thanks for bringing this up, @SteveYuOWO. The README is reflecting the most recent version of the project. But it hasn't been published to npm yet. Closing this as a duplicate of #132. I will leave an update in that thread shortly.

**Closed by markcellus** 2021-11-04 20:51 UTC
